### ISSUE TITLE
TimeAggregation value is showing as null

### ISSUE THREAD

**Issue by akshaykg** [MicrosoftDocs/azure-docs-powershell#1019]
(Get-AzureRmAlertRule -ResourceGroup $resourceGroup -Name $alertN).condition.TimeAggregation  is null but while creating the copy of alert with same condition using Add-AzureRmMetricAlertRule it will not accept null reference.

**Comment by sptramer** [comment]
In order to let you know whether or not this is a bug, I would need to know a lot more about your alert configuration and the expected responses. I would suggest that you contact Azure support services through the Azure Portal: https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview
