### ISSUE TITLE
Uninstall-Allmodules is leaving a trail of sub-modules.

### ISSUE THREAD

**Issue by chaami** [MicrosoftDocs/azure-docs-powershell#1123]
Hi,
The `Uninstall-AllModules` prompted  me with many warnings about what appears to be sub-modules at different versions from the AzureRM umbrella module.
In order to remove the aforementioned sub-modules I have personally used:
```powershell
$modules = (Get-InstalledModule -Name AzureRM.*)
foreach ($module in $modules)
{
  Uninstall-AllModules $module.Name -Version $module.Version -Force
}
```
And now I am left with three persistent buggers:
- AzureRM.ApiManagement at version 5.1.2.
- AzureRM.DataLakeStore at version 5.2.0
- AzureRM.Profile 4.6.0

Any idea how to get rid of those ? (You may want to update the page command as well...)
Cheers and kind regards.

**Comment by sptramer** [comment]
The existing `Uninstall-AllModules` script should be finding those versions which have direct requirements, so this may explain the problem. Some modules are versioned to use a `MinimumVersion` in dependency, which can't necessarily be removed (since an existing module on the system may depend on it.) Without complicating the script further, these modules can't easily be removed, but it is on the backlog.

The recommended way to remove these modules when you know their exact names/versions is to just use the [Uninstall-Module](https://docs.microsoft.com/en-us/powershell/module/powershellget/uninstall-module?view=powershell-6) command.
