### ISSUE TITLE
Really confusing for a beginner

### ISSUE THREAD

**Issue by John-Blair** [MicrosoftDocs/azure-docs-powershell#1243]
&gt;You can't have both the AzureRM and Az modules installed for PowerShell 5.1 for Windows at the same time.

Well, which do i need AzureRM or Az ?- I'm new to powershell on azure 
Why did you create 2 modules that are incompatible with each other - causing a complete mess and i'm only at the install stage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 463a0d17-6457-034a-a5f8-efe5e5d336e7
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-2.8.0)
* Content Source: [docs-conceptual/azps-2.8.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.8.0/install-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by BharathNimmala-MSFT** [comment]
@John-Blair Thank you for your query. 

For Azure PowerShell to have cross-platform support a  [new module Az](https://github.com/Azure/azure-powershell/blob/master/documentation/announcing-az-module.md) was created rather than make modifications to the existing AzureRM module. Moving forward, all new functionality will be added to the Az module, while AzureRM will only be updated with bug fixes. 

If you are starting new, recommedation is to leverage the Az module. 

Documentation Reference - 

[How to migrate from AzureRM to AZ in Azure Powershell](https://azure.microsoft.com/is-is/blog/how-to-migrate-from-azurerm-to-az-in-azure-powershell/)
[Cross Platform Az Module Replacing AzureRM](https://azure.microsoft.com/en-us/blog/azure-powershell-cross-platform-az-module-replacing-azurerm/
)

Hope this information helps, please revert back if you have any further queries.

**Comment by John-Blair** [comment]
The question was:
>Why did you create 2 modules that are incompatible with each other - causing a complete mess

**Comment by BharathNimmala-MSFT** [comment]
@John-Blair Thanks for sharing the feedback, currently loading Az and AzureRM side by side is not a supported scenario. However if you want to have both on one mahcine, you can load AzureRM in Windows Powershell and Az in PowerShell Core. 

Hope this information helps, please let us know if you have any further queries. Thanks

**Comment by BharathNimmala-MSFT** [comment]
@John-Blair Thanks again for your feedback, at this point it appears that there's no further edits or updates needed for the documentation. We would close this issue for now, however if you have any further queries please feel free to tag us in your reply and will be happy to continue the conversation. Thank you.

**Comment by John-Blair** [comment]
The question was:

Why did you create 2 modules that are incompatible with each other - causing a complete mess?

You don't even answer the question asked and then close the issue - fantastic service - can I nominate this as the most useless response to a question?

**Comment by BharathNimmala-MSFT** [comment]
@John-Blair Apologies, if the responses didn't answer your question. We certainly want to provide service/support that upholds our customer expectation. 

Inactive issues make it difficult for us to track what is being worked, since I didn’t had further response for my previous update on the thread ended up closing the issue. However that doesn't mean the conversation has to be over, I have reopened the issue for us to continue the conversation. 

Thanks again for sharing the feedback, the previous responses has been focused on what is the current supportability and limitation of the product and to support a scenario where you wanted to have both the modules what can be done. 

With introduction of [PowerShell Core 6.x](https://docs.microsoft.com/en-us/powershell/scripting/overview?view=powershell-6) based on the .NET Standard library the biggest and most important changes is that PowerShell has been a cross-platform product. To bring Azure support to all platforms, which means that the Azure PowerShell modules needed to be updated to use .NET Standard and be compatible with PowerShell Core. Rather than taking the existing AzureRM module and introduce complex changes to add this support, the Az module was created. 

The Az module has a compatibility mode to help you use existing scripts while you update to the new syntax. The [Enable-AzureRmAlias ](https://docs.microsoft.com/en-us/powershell/module/az.accounts/enable-azurermalias?view=azps-3.0.0) cmdlet enables a compatibility mode through aliases, to allow you to use existing scripts with minimal modification while working towards a full migration to Az. Please be aware of the [full breaking changes list](https://docs.microsoft.com/en-us/powershell/azure/migrate-az-1.0.0?view=azps-3.0.0) to find where your scripts may require updates. 

Please refer to [this additional documentation reference](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-3.0.0#why-a-new-module) on why a new module was introduced. 

I will share your feedback to our internal product and request them to update the thread with any other additional information they can provide to further clarify the query you have.

If you have any other feedback on improving the documentation we have to further help our Azure CLI customers/community please do let us know, will be happy to hear the feedback and see where we can improve. Thank you.

**Comment by John-Blair** [comment]
Thanks for answering - feel free to close.

**Comment by BharathNimmala-MSFT** [comment]
@John-Blair Thank you John.
