### ISSUE TITLE
Command doesn't work

### ISSUE THREAD

**Issue by sannya1803** [MicrosoftDocs/azure-docs-powershell#1272]
Hi, I'm on Windows 10 and PS 5.0 and the instruction doesn't work for me. However, I found other ways that work:
1. Instead of using Uninstall-AzureRm, I can use Uninstall-Module AzureRm
2. To uninstall all of the sub module, I used this command:
foreach ($module in (Get-Module -ListAvailable AzureRM*).Name |Get-Unique) {
   write-host "Removing Module $module"
   Uninstall-module $module
}

source: https://stackoverflow.com/questions/34204373/how-to-clean-up-bad-azure-powershell-uninstall

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbebf43b-1e7c-efcb-139d-b41708fe4ba6
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-3.1.0#feedback)
* Content Source: [docs-conceptual/azps-3.1.0/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.1.0/uninstall-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by MonikaReddy-MSFT** [comment]
@sannya1803 , Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by MonikaReddy-MSFT** [comment]
@sannya1803 , 

The purpose of Uninstall-AzureRm is that it will automatically uninstall the related AzureRm modules. 

As stated in the documentation, Uninstall-Module only uninstalls modules installed using Install-Module. If AzureRM was installed using the MSI package, then it can only be uninstalled using MSI.

Also since PowerShell 5.0 is not supported, you must be on 5.1 to get the commands working.

I hope this information helps. 

Since there are no doc changes required at this moment,  We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
