### ISSUE TITLE
Add link to Migration Guide to Az 1.0.0

### ISSUE THREAD

**Issue by lesterw1** [MicrosoftDocs/azure-docs-powershell#1291]
Recommend adding the following section to this page as the reference has critical information for anyone migration from AzureRm to Az.

## Migrate to Az 1.0.0
To see the changes between the 6.x versions of AzureRM and Az version 1.0.0, visit the [Az 1.00 Migration Guide](https://github.com/Azure/azure-powershell/blob/master/documentation/migration-guides/Az.1.0.0-migration-guide.md).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 700f1288-58ef-e744-257d-593504864265
* Version Independent ID: 3da6471e-bcaf-2b48-5a52-30ef3afebde3
* Content: [Migrate Azure PowerShell scripts from AzureRM to Az](https://docs.microsoft.com/en-us/powershell/azure/migrate-from-azurerm-to-az?view=azps-3.2.0)
* Content Source: [docs-conceptual/azps-3.2.0/migrate-from-azurerm-to-az.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.2.0/migrate-from-azurerm-to-az.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by kobulloc-MSFT** [comment]
@lesterw1 Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by dcaro** [comment]
@lesterw1 thanks for a very good suggestion.
@Minewiskan I think that it make sense to add a pointer to the reference page.

**Comment by mikefrobbins** [comment]
The content in the referenced [Az 1.0.0 Migration Guide](https://github.com/Azure/azure-powershell/blob/master/documentation/migration-guides/Az.1.0.0-migration-guide.md) is the same content contained in the [Breaking changes for Az 1.0.0](https://docs.microsoft.com/powershell/azure/migrate-az-1.0.0) doc that's already linked to seven times in the existing [Migrate Azure PowerShell from AzureRM to Az](https://docs.microsoft.com/powershell/azure/migrate-from-azurerm-to-az) doc.

It's possible that this wasn't the case when this issue was logged and the doc has been updated since.
