### ISSUE TITLE
Best Practice: Securing the Context Cache

### ISSUE THREAD

**Issue by aydeisen** [MicrosoftDocs/azure-docs-powershell#1293]
Is there a best practice for securing the context cache?

Example:
I just had a scenario where I had to wipe and reload my computer.  Before doing so, I backed up my user profile.

I restored the %userprofile%\.Azure directory after the computer was wiped and, after re-enabling the autocontextsave, was able to log into my Azure account without reauthenticating.

While this was convenient for me, this tells me that anyone with my .Azure directory can impersonate me if they copy it to their own location until such a time that my credentials change.  

An seemingly innocuous example:
* A server administrator with access to the file server hosting my redirected profile with access to the could copy my cached credentials to their own profile
    * This opportunity might be taken if the server admin and Azure admin roles are separated, and the server admin doesn't have rights to Azure
    * Potentially, there is no way for me to know that my cached credentials have been lifted without reviewing object access audit logs on the server
        * This also has the potential to be overlooked, as the server administrator might be tasked with manipulating files and folders as part of their responsibilities
    * Azure might have no way to secure against this or effectively audit this access, as the source IP address might be the same or, at the very least, authorized

What would the documented best practices be for securing and/or auditing the Azure Context cache, and what is the best practice actions if the context cache is compromised?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 337dc474-8869-7ca2-6d27-8804add430e1
* Version Independent ID: f641b6fa-c346-ad1d-65a6-793a4bedcbdf
* Content: [Azure contexts and sign-in credentials](https://docs.microsoft.com/en-us/powershell/azure/context-persistence?view=azps-3.2.0#feedback)
* Content Source: [docs-conceptual/azps-3.2.0/context-persistence.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.2.0/context-persistence.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by mike-urnun-msft** [comment]
@aydeisen Thank you for your feedback! I have assigned an engineer who can help with the next steps.

**Comment by SamaraSoucy-MSFT** [comment]
Hi @aydeisen,

Great question! The reality is that many stored credentials are going to be vulnerable to this sort of attack, particularly if they don't have a password required to access them specifically. [Browser cookies](https://security.stackexchange.com/questions/203737/browser-session-cookies-stolen-copied-to-another-pc-why-websites-not-smart-enou) have the same weakness. It's possible to copy the cookie file from one machine to another and access all the sites through them. The same thing happens if you use SSH without a password protecting your private key.

Similar to being able to wipe cookies between browser sessions, you can [clear the context](https://docs.microsoft.com/en-us/powershell/azure/context-persistence?view=azps-3.3.0#save-azure-contexts-across-powershell-sessions) between uses. `Disable-AzContextAutosave` disables this default behavior. You could also store the context in an encrypted folder that the server admin does not have access to and import it with `Import-AzContext -Path other-context.json`. 

Making sure that your user has the minimum required permissions and using [resource locks](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/lock-resources) to prevent edits and/or deletes where appropriate will help to mitigate any possible damage if your account is compromised. Azure does attempt to detect risky sign-in behavior and it [can be setup](https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/concept-sign-ins) to alert admins when this happens. As you noted though, this scenario wouldn't necessarily be caught by this sort of monitoring as the access would be similar to legitimate traffic.

If someone has gotten access this way, the [Azure Activity Log](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/activity-log-view) has detailed information about what has happened to each resource, who made the change, and how it was accomplished. That will allow you to find out what was done and reverse as much as possible. Depending on the data type, the support team may also be able to assist with recovering any data that was deleted and you are unable to retrieve. What support can assist with is going to be situational- I can't make any guarantees about what is and is not possible.

Revoking access once the issue is detected is possible. Changing your password is always a good precaution but isn't required in the case where only a token is compromised. 

When authenticating to AAD, you actually receive two tokens- your access token and a refresh token. Once the access token expires the refresh token is used to retrieve a new one without having to sign in again. The access token, which is what is used to actually modify your account, cannot be revoked, so the unauthorized party would have control of your account as long as that lasts. However, for that exact reason, these tokens aren't good for very long. The [default setting ](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes)is for each access token to last for only an hour. This can be configured to as little as 10 minutes, but the shorter this window is, the more often your system has to go back to Azure AD for a new token which impacts performance.

The refresh token can be revoked, and this is where it would be possible to cut off access. While it doesn't stop the person from immediately using your access token, it would stop them from being issued a new one. If you used a password login to generate the token, then changing your password invalidates the refresh token. If you used another method, like Windows Hello, then [changing the password](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#validating-tokens) does not help, but the refresh token can still be revoked via Powershell.

If you suspect that your token has been compromised then you [should run](https://docs.microsoft.com/en-us/powershell/module/azuread/revoke-azureadsignedinuserallrefreshtoken?view=azureadps-2.0) the `Revoke-AzureADSignedInUserAllRefreshToken` command to invalidate all the refresh tokens attached to your account. This includes app tokens like your Powershell context as well as web cookies. If there is any suspicion that your account is not the only one compromised in this way, which is very possible in the scenario you describe, then the account admin [can revoke all refresh tokens](https://docs.microsoft.com/en-us/powershell/module/azuread/revoke-azureaduserallrefreshtoken?view=azureadps-2.0) for the organization using the `Revoke-AzureADUserAllRefreshToken`.
