### ISSUE TITLE
Failed To Create PSCredential

### ISSUE THREAD

**Issue by MegoCs** [MicrosoftDocs/azure-docs-powershell#1310]
when i tried to login with the principal to my tenant using those commands 

$passwd = ConvertTo-SecureString 'Sp-Secret'-AsPlainText -Force
$pscredential = New-Object System.Management.Automation.PSCredential('$sp.DisplayName/Id', $passwd)
Connect-AzAccount -ServicePrincipal -Credential $pscredential -Tenant "T-Id"

but it can't find the service principal. but what i found is instead of sp.DisplayName/id it needs the principal Application Id

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce9bf0ab-d55f-3da2-5320-2f6d33f993fd
* Version Independent ID: b814f076-657c-206b-b16e-c7f137bff744
* Content: [Sign in with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-3.3.0)
* Content Source: [docs-conceptual/azps-3.3.0/authenticate-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.3.0/authenticate-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by TravisCragg-MSFT** [comment]
@MegoCs Thanks for the feedback. We are actively investigating and will get back to you soon.

**Comment by MohitVerma-MSFT** [comment]
Hello @MegoCs ,

**Username/password** credential authorization has been removed in **Azure PowerShell** due to changes in Active Directory authorization implementations and security concerns. If you use credential authorization for automation purposes, instead [create a service principal.](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-3.3.0)

below is the code for the same:

```
$passwd = ConvertTo-SecureString <use a secure password here> -AsPlainText -Force
$pscredential = New-Object System.Management.Automation.PSCredential('service principal name/id', $passwd)
Connect-AzAccount -ServicePrincipal -Credential $pscredential -Tenant $tenantId
```

You can find the further reference in below doc link:

https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-3.3.0#password-based-authentication

**Comment by MohitVerma-MSFT** [comment]
Hello @MegoCs ,

Just wanted to check if you got a chance to check my previous response.

**Comment by MohitVerma-MSFT** [comment]
Hello @MegoCs ,

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue. Thanks for bringing this to our attention. We will now close
 this issue. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion. We will close this out, but if you feel you need more information please just let us know.
