### ISSUE TITLE
zureRM.Profile already loaded. Az and AzureRM modules cannot be imported in the same session or used in the same script or runbook

### ISSUE THREAD

**Issue by Praveen6867** [MicrosoftDocs/azure-docs-powershell#1343]
I am getting the below error for Command "**Connect-AzAccount**" or " **Import-Module -Name Az -RequiredVersion 3.6.1**"

Please let us know how to resolve this issue. 
Thanks in advance 

WARNING: AzureRM.Profile already loaded. Az and AzureRM modules cannot be imported in the same session or used in the same script or runbook. If you are running Po
werShell in an environment you control you can use the 'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine. If you are running in Azure Auto
mation, take care that none of your runbooks import both Az and AzureRM modules. More information can be found here: https://aka.ms/azps-migration-guide.
Import-Module : AzureRM.Profile already loaded. Az and AzureRM modules cannot be imported in the same session or used in the same script or runbook. If you are 
running PowerShell in an environment you control you can use the 'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine. If you are running 
in Azure Automation, take care that none of your runbooks import both Az and AzureRM modules. More information can be found here: 
https://aka.ms/azps-migration-guide.
At line:1 char:1
+ Import-Module -Name Az -RequiredVersion 3.6.1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (AzureRM.Profile...igration-guide.:String) [Import-Module], RuntimeException
    + FullyQualifiedErrorId : AzureRM.Profile already loaded. Az and AzureRM modules cannot be imported in the same session or used in the same script or runbook 
   . If you are running PowerShell in an environment you control you can use the 'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine. If   
  you are running in Azure Automation, take care that none of your runbooks import both Az and AzureRM modules. More information can be found here: https://aka   
 .ms/azps-migration-guide.,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by femsulu** [comment]
Hi @Praveen6867 : according to the output u shared, the error seems to be due to a PS Module conflict. This usually happens when you try to load both the older AzureRM and newer Az modules onto the same PS session - these 2 modules are incompatible. Check the refrences below for more information.
1. [Introducing the Azure PowerShell Az Module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-3.6.1).
2. [Installing Azure PowerShell AzureRM module](https://docs.microsoft.com/en-us/powershell/azure/azurerm/install-azurerm-ps?view=azurermps-6.13.0#install-the-azure-powershell-module)
![image](https://user-images.githubusercontent.com/34327711/76922171-33629e80-688d-11ea-8615-ca6d6533b8ae.png)

You have 2 options to resolve this depending on which module your scripts were built on. If your scripts were authored using Az cmdlets then use option 1. If Azure RM, then use option 2. 

1.)  Use 'Uninstall-AzureRm' cmdlet to remove all AzureRm modules, Import Az module only, use the Az cmdlets e.g. 

- "Connect-AzAccount"  ,
-  Import-Module -Name Az -RequiredVersion 3.6.1"

2.) Use 'Uninstall-Az' cmdlet to remove all Az modules, Import AzureRM Module only, use the AzureRM cmdlets e.g.

-  "Connect-AzureRmAccount"  , 
- "Import-Module -Name AzureRM -RequiredVersion 2.3.0"

Hope that helps.

Cheers.

**Comment by femsulu** [comment]
Hi @Praveen6867 . Hope my comments above helped your case. We will now close this issue. If there are further questions regarding this matter, please reply and we will gladly continue the discussion.

**Comment by Praveen6867** [comment]
Thanks this helped me.

**Comment by ShehzadUIT** [comment]
Hi, How to takecare of this issue in Azure Automation runbook?
