### ISSUE TITLE
Please clarify which permissions are needed

### ISSUE THREAD

**Issue by LouisDK** [MicrosoftDocs/azure-docs-powershell#1350]
The code to create a new SP works when executed as a User (with AzureAD admin rights).
When trying to create a new Service Principal when the code runs as another Service Principal, it fails while complaining about Insufficient Privileges. 
Context: I'm writing an Azure Function (PowerShell or C#) that needs to create a Service Principal. Since it appears that Managed Identities (MSI) cannot be granted permissions to do this (?), I'm assuming that the Azure Function code should authenticate as pre-existing Service Principal A (which has been granted permissions), and then try to create Service Principal B.
In my environment, it would not be acceptable to make Service Principal A an AzureAD Administrator (unless there is no way around it).

Q1: Am I correct in stating that a Managed Identity (MSI) cannot create Service Principals?
Q2: What permissions would a Service Principal need to create other Service Principals?
Q3: What APIs are used by the new Az module? (Where should the permissions be assigned? GraphAPI? Azure Active Directory Graph? Somewhere else?)
Q4: Does the Service Principal (who tries to create the other Service Principals) need to have any Roles in an Azure Subscription?
Q5: Any chance of a code example on how to do this? Given the many questions on the internet about this, it seems enough people are trying to do this to warrant an official example / guidance around this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6a975e2-e8d1-f0f3-80ec-307b6274ab74
* Version Independent ID: 84b2cbcb-1f11-9a6d-23fd-5c8d76453fa8
* Content: [Use Azure service principals with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-2.8.0#feedback)
* Content Source: [docs-conceptual/azps-2.8.0/create-azure-service-principal-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.8.0/create-azure-service-principal-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by BharathNimmala-MSFT** [comment]
@LouisDK Thank you for your query, our team will look into it and get back to you at the earliest.

**Comment by SamaraSoucy-MSFT** [comment]
I'm going to add the doc author to this question to see about making the additional documentation.

1) You can do this with either a Managed Identity or Service Principal assuming the app has the required permissions.
2) You may want to create a custom role for this that has just the few permissions needed to accomplish this so you can limit what you are giving to the app. To use built in roles, you can use [Application Administrator](https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles#role-permissions) (to create the SP) and [User Access Administrator](https://docs.microsoft.com/en-us/rest/api/authorization/role-assignment-rest-sample) (to add the new SP to any needed roles).
-- Microsoft.Authorization/roleAssignments/write
-- Microsoft.Directory/applications/create
-- Microsoft.Directory/servicePrincipals/create
3) In this case, it is using AAD Graph and the Management API. If you ever want to see what calls the CLI is making, use the --debug flag and all the relevant information will be output to the console.

Once you have the correct permissions setup, doing this in Powershell with the CLI should be a matter of following the doc here: https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest, other than that the login becomes `az login --identity`. 

The `Microsoft.Azure.Management.Fluent` library will help quite a bit if you want to do this in C#. There's a sample here that includes setting up a new Service Principal: https://github.com/Azure-Samples/aad-dotnet-manage-users-groups-and-roles/blob/master/Program.cs. Instead of loading the credentials from file, you'll be using wither Managed Identity or Service Principal.

**Comment by mikefrobbins** [comment]
Specific details about the necessary permissions have been provided in the previous response.
