### ISSUE TITLE
Creating service principal creates an app in Active directory

### ISSUE THREAD

**Issue by jeevaeastpoint** [MicrosoftDocs/azure-docs-powershell#1377]
I am curious to know why creating a service principal also creates an app. We have two PowerShell commands New-AzADServicePrincipal and New-AzADApplication which creates an app. The only difference is that in case of service principal we have a secret created which by default has a "Contributor" access to the subscription (which is weird allowing Contributor access by default!!!). Where in the app doesn't have a secret created by default.... Do we have any explanation on this? Any docs to clear the differentiation between Service Principal and Azure AD App.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be8ceec6-fcb5-fe91-52dc-6975a533f61f
* Version Independent ID: 84b2cbcb-1f11-9a6d-23fd-5c8d76453fa8
* Content: [Use Azure service principals with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-3.8.0)
* Content Source: [docs-conceptual/azps-3.8.0/create-azure-service-principal-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.8.0/create-azure-service-principal-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by SamaraSoucy-MSFT** [comment]
Thanks for the question! We will review and get back to you shortly.

**Comment by jeevaeastpoint** [comment]
I am also interested to know whether the Service principal treated or used as Azure AD App

**Comment by SamaraSoucy-MSFT** [comment]
There are some existing docs on this concept in the Identity platform docs:
https://docs.microsoft.com/en-us/azure/active-directory/develop/app-objects-and-service-principals
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-how-applications-are-added

To try and summarize, every service principal is connected to an app, and an app has at least one service principal.

**App:** Lives inside of Azure AD, which is a global resource and not part of your tenant. That's why you can add users and apps that were created in one tenant to another. This is the part that handles the authentication side of things.

**Service Principal:** This part lives inside of your tenant and handles access control to resources. An app has a service principal in every tenant that it has access to. It is the part that authorizes a specific action for your application. 

Users have the same construct in the form of a user principal, but the distinction doesn't come up as often.

Does that help to clarify things, or do you have further questions? I know this concept isn't always the easiest to understand.

**Comment by SamaraSoucy-MSFT** [comment]
Since I have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly reopen the issue and continue the discussion.
