### ISSUE TITLE
Set-AzSqlDatabaseVulnerabilityAssessmentRuleBaseline not working properly with single rule

### ISSUE THREAD

**Issue by CharmanderJieniJieni** [MicrosoftDocs/azure-docs-powershell#1421]
The BaselineResult parameter cannot accept single line of input. Say 
Set-AzSqlDatabaseVulnerabilityAssessmentRuleBaseline `
     -ResourceGroupName $rgname `
     -ServerName $serverName `
     -DatabaseName $databasename `
     -RuleId "VA2108" `
     -BaselineResult @( 'Principal1' , 'db_ddladmin', 'SQL_USER','DATABASE')

Result showing in portal is not parsing correctly 
https://user-images.githubusercontent.com/37126106/83715214-bfa97580-a5e1-11ea-8d6b-fd2dd3dcf90e.png

**Comment by MonikaReddy-MSFT** [comment]
@CharmanderJieniJieni , Thanks for brining this to our attention. 

Can you provide us the doc that you are using, so we can investigate it further.

**Comment by Mike-Ubezzi-MSFT** [comment]
@MonikaReddy-MSFT This is a potential issue with the following cmdlet [Set-AzSqlDatabaseVulnerabilityAssessmentRuleBaseline](https://docs.microsoft.com/en-us/powershell/module/az.sql/Set-azSqlDatabaseVulnerabilityAssessmentRuleBaseline?view=azps-4.2.0) where the cmdlet requires at least two parameters for the `BaselineResult`. Customer has been requested to open an issue on this repository specifically, as it is a PowerShell issue and not an issue with the MicrosoftDocs page (per issue [56304](https://github.com/MicrosoftDocs/azure-docs/issues/56304)).

**Comment by Mike-Ubezzi-MSFT** [comment]
If only a single entry for `BaselineRule`
 is passed, the Assessment Rule results are skewed when viewing the results in the Azure Portal:

![Screenshot (51)](https://user-images.githubusercontent.com/37126106/83794381-ca502300-a652-11ea-8624-ea4d31e42e69.png)

![Screenshot (50)](https://user-images.githubusercontent.com/37126106/83794515-fcfa1b80-a652-11ea-9dd9-4495076f92ae.png)

**Comment by Mike-Ubezzi-MSFT** [comment]
If you pass two parameters, the data is displayed correctly:

![Screenshot (45)](https://user-images.githubusercontent.com/37126106/83794808-611cdf80-a653-11ea-9649-6fbc270019b6.png)

![Screenshot (46)](https://user-images.githubusercontent.com/37126106/83794838-6bd77480-a653-11ea-96d0-35cb26b32789.png)

**Comment by MonikaReddy-MSFT** [comment]
@Mike-Ubezzi-MSFT - Thanks for providing more insights on this. This repo is for Azure Docs PowerShell. Since this is a product issue, I have opened this issue against Product Team Repo which is this - https://github.com/Azure/azure-powershell . 

@CharmanderJieniJieni - Thanks again for bringing this to our attention. We have raised the issue in PowerShell PG Repo and the Product team should be working on the issue.  At this moment, We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
