### ISSUE TITLE
 AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'

### ISSUE THREAD

**Issue by yaobaobao2002** [MicrosoftDocs/azure-docs-powershell#1460]
I would like to connect AzAccount without manual input username and password. I use below code.
Quote: $User = "xxxxxxxxxx"
$PWord = ConvertTo-SecureString -String "xxxxxxxxxx" -AsPlainText -Force
$Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $User, $PWord
Connect-AzAccount -Credential $Credential 
UnQuote

There is error saying "AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'"

I;m afraid I have no access right to MFA? How to solve this problem , so that I can automatic log in Azure

**Comment by MonikaReddy-MSFT** [comment]
@yaobaobao2002 - Thank you for your question. 

Can you please share with us the URL of the document that you are having issues with?

Please note that we scope issues on this repo to feedback related to the docs. If you have a product question, please post it on MSDN or Stack Overflow. Thank you for your understanding.

**Comment by yaobaobao2002** [comment]
https://docs.microsoft.com/en-us/powershell/module/az.accounts/Connect-AzAccount?view=azps-4.3.0
https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-4.3.0

**Comment by MonikaReddy-MSFT** [comment]
@mikefrobbins - Do you have any insights on the above?

**Comment by mikefrobbins** [comment]
The specified docs don't reference MFA because service principals don't support MFA. Based on my research, this is occurring because security defaults have been enabled for your tenant that are being applied automatically to the new service principal that you're trying to create. For more information, see "[What are security defaults](https://docs.microsoft.com/azure/active-directory/fundamentals/concept-fundamentals-security-defaults)?".

**Comment by MonikaReddy-MSFT** [comment]
@mikefrobbins  - Thank you for providing your insights.
@yaobaobao2002 -  I hope @mikefrobbins has answered your question. 
At this moment, Since there is no doc update required, We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
