### ISSUE TITLE
Inconsistent doc

### ISSUE THREAD

**Issue by awf** [MicrosoftDocs/azure-docs-powershell#1519]
This page says 
> The following example removes all AzureRM modules from your machine.

But running the command gives this message. which is contradictory:
```
> Uninstall-AzureRm
WARNING: Running this cmdlet in PowerShell Core will only remove the modules from PowerShell Core. Please rerun this cmdlet in a PowerShell 5.1 session to remove the modules from PowerShell 5.1.
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff006e2c-7cd3-efec-be79-fd2b1a570d6d
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-4.5.0#uninstall-the-azurerm-module)
* Content Source: [docs-conceptual/azps-4.5.0/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-4.5.0/uninstall-az-ps.md)
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by MonikaReddy-MSFT** [comment]
@awf -
Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by MonikaReddy-MSFT** [comment]
Hello @awf  -  AzureRM is only supported in Windows PowerShell, not PowerShell Core. And it looks like you are using PowerShell Core. 

At this moment, Since there is no doc update required, We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
