### ISSUE TITLE
This article is astoundingly confusing. First, Don't install Azure AZ, then ten ways to override that advice and install it?

### ISSUE THREAD

**Issue by kimballjohnson** [MicrosoftDocs/azure-docs-powershell#1545]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 108ead93-fd5d-f4c6-c3ee-0f4c6478e8dd
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-4.6.0)
* Content Source: [docs-conceptual/azps-4.6.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-4.6.0/install-az-ps.md)
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by kobulloc-MSFT** [comment]
@kimballjohnson Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by kobulloc-MSFT** [comment]
@kimballjohnson It is confusing, especially if you are new to PowerShell.  I'm sorry about that.  The documentation talks a bit about [why the decision was made to introduce a new module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-4.6.0#why-a-new-module) and we believe that the benefits of the new module warranted the change.

Hopefully this will help clear up some common points of confusion:

- PowerShell 7.x and later is currently the newest version and we recommend using that.
- Azure Powershell has no additional requirements as long as it's run on PowerShell 6.2.4 or later (another reason to use PowerShell 7.x).
- If you are using PowerShell 5.1 (which is already installed on more recent versions of Windows 10) instead of a more recent version of PowerShell, you'll need to follow the installation instructions.
- There's a workaround if you need AzureRM for legacy reasons that involves installing AzureRM on PowerShell 5.1 and Az module on PowerShell 6.2.4 or later (as you can't have both the older AzureRM module and Az modules installed on PowerShell 5.1).

**Comment by kobulloc-MSFT** [comment]
@kimballjohnson Hopefully that helps to clear up some of the confusion!  We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by kimballjohnson** [comment]
Ok, thanks for rewriting the content of the article.
My question is about the irony and confusion of the article’s clear message that AzureRM and AZ should not be deployed to a system simultaneously, while simultaneously providing instructions for simultaneously deploying both of them in every variety of installation scenario.
If they are not to be deployed together, what more needs to be said, unless you want responsible people to try what you are advising them not to do?
Let’s not try to explain it, or just agree that you are not sure whether they will successfully coexist!

**Comment by kobulloc-MSFT** [comment]
@kimballjohnson If you are getting a fresh start, PowerShell 7 and the AZ module is the recommendation.  If you already have legacy processes that depend on the AzureRM module and cannot migrate at this time for one reason or another, then you'll need to use the workaround described in the documentation.
