### ISSUE TITLE
Uninstall-AzureRm not found even though AzureRm is installed.

### ISSUE THREAD

**Issue by lovettchris** [MicrosoftDocs/azure-docs-powershell#1557]
Clean windows 10 install, AzureRM was installed and I need to remove it to get the new Az module, but the pages says to use Uninstall-AzureRm but I get this error:

```
Uninstall-AzModule : The term 'Uninstall-AzModule' is not recognized as the name of a cmdlet
```

I had to use this instead from an admin prompt:

```
Uninstall-Module AzureRM
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 873500f9-ae68-2bdd-9956-01a5904c5a06
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-4.6.1#uninstall-the-azurerm-module)
* Content Source: [docs-conceptual/azps-4.6.1/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-4.6.1/uninstall-az-ps.md)
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by kobulloc-MSFT** [comment]
@lovettchris Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by kobulloc-MSFT** [comment]
@lovettchris Thank you for bringing this to our attention!  I wanted to confirm that I'm seeing the same thing you are.  I'm following up internally to make sure that I've got the most up to date instructions for uninstalling AzureRm as this is listed in a couple locations and Uninstall-Module leaves a number of AzureRm modules on the machine.

![image](https://user-images.githubusercontent.com/37556655/92881858-3665c400-f3c4-11ea-8b1f-67c3ca4e7985.png)

![image](https://user-images.githubusercontent.com/37556655/92881896-4382b300-f3c4-11ea-9834-e084f6ac8869.png)

![image](https://user-images.githubusercontent.com/37556655/92881930-4aa9c100-f3c4-11ea-833c-ad3b91a507d8.png)

![image](https://user-images.githubusercontent.com/37556655/92882092-7167f780-f3c4-11ea-9307-458e035a61c1.png)

**Comment by lovettchris** [comment]
Yes, looks like you have a repro, thanks for investigating.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by mikefrobbins** [comment]
@lovettchris Please see the [Uninstall the AzureRM module](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-4.6.1/uninstall-az-ps.md#uninstall-the-azurerm-module) section of the referenced doc.

Simply install the Az PowerShell module as referenced in the doc. The easiest way to accomplish this is to install it from PowerShell using the PowerShell gallery: `Install-Module -Name Az`.

The Az PowerShell module adds a cmdlet named `Uninstall-AzureRM` which can be used to remove the AzureRM PowerShell module.

The AzureRM PowerShell module is a wrapper for numerous other modules which is why `Uninstall-Module -Name AzureRM` doesn't perform a full uninstall. It only uninstalls the wrapper module.

Depending on what state your system is currently in, you may have to use this command to cleanup the AzureRM modules: `Get-InstalledModule -Name AzureRM, AzureRM.* | Uninstall-Module`

**Comment by kobulloc-MSFT** [comment]
@lovettchris I missed the Az PowerShell module requirement as well.  In the interest of documenting this for anyone else who may run into this issue, this was the shortest path I found to a complete AzureRm install and uninstall (run on Windows 10).


**Install AzureRm module**
`Install-Module -Name AzureRM -AllowClobber`

**Check to see that AzureRm is installed**
`Get-InstalledModule`

**Install Az PowerShell module**
`Install-Module -Name PowerShellGet -Force`
`Install-Module -Name Az -AllowClobber -Scope CurrentUser`   (This avoids the "Warning: Az module not installed.  Having both the AzureRM and Az Modules installed at the same time is not supported." you encounter from running the script in the documentation.)

**Uninstall AzureRm module**
`Set-ExecutionPolicy RemoteSigned`   (This avoids the error: "The 'Uninstall-AzureRm' command was found in the module 'Az.Accounts', but the module could not be loaded.")
`Uninstall-AzureRm`

**Confirm that all AzureRm modules have been uninstalled**
`Get-InstalledModule`


I'll add screenshots for additional clarity.

**Comment by kobulloc-MSFT** [comment]
@lovettchris We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
