### ISSUE TITLE
Catch-22: Uninstalling AzureRM module requires installing Az module

### ISSUE THREAD

**Issue by tushar-bhargava-ms** [MicrosoftDocs/azure-docs-powershell#1573]
I was following the instructions for [installing the Az module](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-4.7.0#install-the-azure-powershell-module) when I realized I'd need to uninstall the AzureRM module first since the Az module installation script would report an error if the AzureRM module was present:

```powershell
if ($PSVersionTable.PSEdition -eq 'Desktop' -and (Get-Module -Name AzureRM -ListAvailable)) {
    Write-Warning -Message ('Az module not installed. Having both the AzureRM and ' +
      'Az modules installed at the same time is not supported.')
} else {
    Install-Module -Name Az -AllowClobber -Scope CurrentUser
}
```

However, when I followed the instructions for [uninstalling the AzureRM module](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-4.7.0#uninstall-the-azurerm-module), I realized it required the Az.Accounts module to run [the Uninstall-AzureRm command](https://docs.microsoft.com/en-us/powershell/module/az.accounts/uninstall-azurerm?view=azps-4.7.0).

This is a catch-22 situation.

I circumvented the situation by installing the Az module while I still had the AzureRM module installed and then running the Uninstall-AzureRm command. It seemed to work. However, the current docs (and included script) seem to strongly discourage installing the Az module first.

The docs should be updated to clarify this situation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b65f02d-8698-ae21-9a8d-e6d167091e2e
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-4.7.0#uninstall-the-azurerm-module)
* Content Source: [docs-conceptual/azps-4.7.0/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-4.7.0/uninstall-az-ps.md)
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by kobulloc-MSFT** [comment]
@tushar-bhargava-ms Thank you for opening this issue.  I was just discussing this today and agree that the docs should be updated to better address this scenario.  There are two resolutions from [1557](https://github.com/MicrosoftDocs/azure-docs-powershell/issues/1557), and the preferred course of action is to install the Az module and use Uninstall-AzureRM like you did.  I'll get this updated shortly.

**Comment by kobulloc-MSFT** [comment]
@tushar-bhargava-ms We've gone through the AzureRM removal instructions and added some clarity in a few areas:

- Sections are now more clearly identified.  Finding the uninstall instructions for a given scenario should be easier.
- The prerequisite of having the Az module installed in order to use the Uninstall-AzureRm command has been made clearer.
- A brief description of why the reader would temporarily have both modules installed in order to remove AzureRM is included.
- Installation instructions for the Az module are provided so that readers don't run into the warning they would otherwise hit if they used the Az.

Thank you again for submitting this issue.  The changes should go live shortly.  We're going to close this issue as resolved but if you feel that additional clarity is needed, please tag me in your reply and we'd be happy to revisit this.
