### ISSUE TITLE
AzureStack 1.7.2 module installation issue

### ISSUE THREAD

**Issue by HassanAlmanasrah** [MicrosoftDocs/azure-docs-powershell#1580]
While customer was installing version 1.7.2, the below error was appearing

The version '0.2.3' of the module 'Azs.Storage.Admin' being installed is not catalog signed. Ensure that the version '0.2.3' of the module 'Azs.Storage.Admin' has the catalog file 'Azs.Storage.Admin.cat' and signed with the same publisher 'CN=Microsoft
Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' as the previously-installed module 'Azs.Storage.Admin' with version '0.3.1' under the directory 'C:\Program Files\WindowsPowerShell\Modules\Azs.Storage.Admin\0.3.1'. If you still want to install or
update, use -SkipPublisherCheck parameter., update aborted.

Version 1.8.2 was installed, and there is automated script that was installing version 1.7.2, which is not acceptable to be modified by customer to add switch -SkipPublisherCheck, could you help advising why the catalog file is missing , or what is wrong here?

**Comment by SamaraSoucy-MSFT** [comment]
Thanks for the question! We will review and get back to you shortly.

**Comment by SamaraSoucy-MSFT** [comment]
Thank you for your feedback! Since this channel is for driving improvements towards MS Docs, could you provide the URL of the specific documentation that your feedback is applicable to? That way, we are able to make sure your feedback is addressed by the right team.

The best place for specific answers about implementations are going to be the [Microsoft Q&A](https://docs.microsoft.com/answers/) and [Stack Overflow](stackoverflow.com) forums. We actively look through posts in the forums, and will do our best to get you going in the right direction!

**Comment by SamaraSoucy-MSFT** [comment]
Just checking in. Could you please provide the relevant documentation so we can route this question appropriately?

**Comment by HassanAlmanasrah** [comment]
customer was installing AzureStack module 1.7.2 on VM , which has already 1.8.2 installed. This was required from OEM  to be installed. Customer got above error message which is related to Azs.Storage.Admin module
https://docs.microsoft.com/en-us/powershell/module/azs.storage.admin/?view=azurestackps-2.0.1&viewFallbackFrom=azurestackps-2.5.0

**Comment by SamaraSoucy-MSFT** [comment]
I've opened an issue on the product repo for that module: [https://github.com/Azure/azurestack-powershell/issues/51](https://github.com/Azure/azurestack-powershell/issues/51). I've also reached out to the product team directly.

Since it doesn't require changes to the documentation, I do need to close the issue here. However, I do encourage you to subscribe to the issue on the product repo. If I get a response from the product team internally I will keep you updated.

**Comment by SamaraSoucy-MSFT** [comment]
@HassanAlmanasrah I wanted to check in and see if the solution posted on the product repo worked for you. If you are able to run commands before the automated script then uninstalling 1.8.2 and deleting the folder in the Powershell directories should resolve the error.

The issue happens only when trying to install 1.7.2 side by side with 1.8.2

> With some testing I was able to get it to work this way:
> 
> Install-Module -Name AzureStack -RequiredVersion 1.8.2 # Preinstalled version
> Get-Module -Name Azs.* -ListAvailable | Uninstall-Module -Force -Verbose -ErrorAction Continue
> Remove-Item "C:\Program Files\WindowsPowerShell\Modules\AzureStack" -Recurse -Force
> Install-Module -Name AzureStack -RequiredVersion 1.7.2
