### ISSUE TITLE
Scripts Wrong

### ISSUE THREAD

**Issue by smitz1** [MicrosoftDocs/azure-docs-powershell#1669]
The line of code

$sp.secret | ConvertFrom-SecureString -AsPlainText

-AsPlainText is not a valid parameter on PowerShell 5.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7880307f-88c6-27bd-3826-76d8e742f194
* Version Independent ID: 84b2cbcb-1f11-9a6d-23fd-5c8d76453fa8
* Content: [Use Azure service principals with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-5.2.0)
* Content Source: [docs-conceptual/azps-5.2.0/create-azure-service-principal-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-5.2.0/create-azure-service-principal-azureps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by kobulloc-MSFT** [comment]
@smitz1 Thank you for the feedback!  I'm not seeing the code sample you mentioned on the page this was opened against (many references to $sp, but nothing on $sp.secret).  Would you mind providing a link?  You would need to use [PowerShell 7 or later](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/convertfrom-securestring?view=powershell-7), because "-AsPlainText" is not documented as supported in [PowerShell 5.1](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/convertfrom-securestring?view=powershell-5.1).

**Comment by kobulloc-MSFT** [comment]
(Test comment)

**Comment by kobulloc-MSFT** [comment]
@smitz1 You are correct that "-AsPlainText" is not supported in PowerShell 5.1.  You would need PowerShell 7 or later.  I don't see any additional corrections to be made in the documentation so we are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
