### ISSUE TITLE
Get-AzRecoveryServicesVault throws Assembly "Microsoft.Azure.PowerShell.Authentication, Version=1.9.0.0

### ISSUE THREAD

**Issue by andreasmarx** [MicrosoftDocs/azure-docs-powershell#1696]
Hi.

I am getting this error with new modules 5.4.0 using "Get-AzRecoveryServicesVault":

Get-AzRecoveryServicesVault : Operation failed.
Die Datei oder Assembly "Microsoft.Azure.PowerShell.Authentication, Version=1.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.                                                                                                                                                                ann die angegebene Datei nicht finden.
In C:\Users\am\vm-deployment\deploy-vm-code_V4.6.ps1:1157 Zeichen:24
+         $choicearray = Get-AzRecoveryServicesVault | where {$_.Locati ...
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzRecoveryServicesVault], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.RecoveryServices.GetAzureRmRecoveryServicesVaults

This issue is not with Version 5.3.0.

Could please someone look into this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f87d802-0d3b-602c-4e4e-b519bb003063
* Version Independent ID: 92f67fd1-c7b3-7afb-0009-9a2cc19187b8
* Content: [Azure PowerShell release notes](https://docs.microsoft.com/en-us/powershell/azure/release-notes-azureps?view=azps-5.4.0#feedback)
* Content Source: [docs-conceptual/azps-5.4.0/release-notes-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-5.4.0/release-notes-azureps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@andreasmarx Thanks for the feedback. We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@andreasmarx I could not reproduce the issue on my end. Here are the modules I have installed on my machine:
```
PS C:\> Get-InstalledModule -Name Az, Az.Accounts, Az.RecoveryServices

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
5.4.0                Az                                  PSGallery            Microsoft Azure PowerShell - Cmdlets to manage resources in Azure. This mo...
3.3.0                Az.RecoveryServices                 PSGallery            Microsoft Azure PowerShell - Recovery Services cmdlets for Azure Resource ...
2.2.4                Az.Accounts                         PSGallery            Microsoft Azure PowerShell - Accounts credential management cmdlets for Az...
```
However, it seems like similar issues with the `Az.RecoveryServices` module were reported in the past:

- https://github.com/Azure/azure-powershell/issues/8417
- https://github.com/Azure/azure-powershell/issues/12230
- https://github.com/Azure/azure-powershell/issues/12468

Please run the following:
```
Install-Module -Name Az.Accounts -Force
Install-Module -Name Az.RecoveryServices -Force
```
and then try `Get-AzRecoveryServicesVault` in a new PS session. Do let me know what you see.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@andreasmarx Hope the above inputs help. Are there any further questions here?

**Comment by andreasmarx** [comment]
@BhargaviAnnadevara-MSFT  I had the issue with AZ 5.4.0 and az.recoveryServices 3.3.0. The issues was reproducable. With AZ 5.3.0 and az.recoveryServices 3.2.0 it is working fine.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@andreasmarx As mentioned in the GitHub issues reeferenced above, there seem to be some assembly conflicts between `Az.RecoveryServices` and `Az.Accounts` modules, which is why I suggested you test with the latest version (**2.2.4**) of `Az.Accounts` module.

Have you had a chance to run this:

> Please run the following to get the latest versions of `Az.Accounts` and `Az.RecoveryServices`:
> ```
> Install-Module -Name Az.Accounts -Force
> Install-Module -Name Az.RecoveryServices -Force
> ```
> and then try `Get-AzRecoveryServicesVault` in a new PS session. Do let me know what you see.

If the problem still persists, please open a new issue with the [Azure PowerShell](https://github.com/Azure/azure-powershell) repo for our Engineering Team to investigate further: [Az module bug report](https://github.com/Azure/azure-powershell/issues/new?assignees=&labels=needs-triage&template=az-module-bug-report.md&title=).

Also, on a side note, I'd like to let you know that this channel (the [Azure PowerShell Docs](https://github.com/MicrosoftDocs/azure-docs-powershell) repository) is only for driving improvements related to documentation on the [Azure PowerShell module](https://docs.microsoft.com/en-us/powershell/azure). The best place for specific answers about implementations is going to be the [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) and [Stack Overflow](https://stackoverflow.com/questions/tagged/powershell) platforms. We actively look through posts in the forums and will do our best to get you going in the right direction.

**Comment by andreasmarx** [comment]
@BhargaviAnnadevara-MSFT As I already mentioned the issue happens with the newest modules. Downgrading to the previous versions works for me. Sorry, I don't have time at the moment to reproduce the issue again and provide all the details requested. From my side you can close this. If I run into the issue again, I will open a bug report and provide details. Thanks for your support.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@andreasmarx Thanks for the response. We will now proceed to close this thread, but if there are any further questions regarding the Azure PowerShell documentation, please tag me in your reply and we will be happy to continue the conversation.
