### ISSUE TITLE
PowerShell Functions concurrent worker process sample

### ISSUE THREAD

**Issue by Ayanmullick** [MicrosoftDocs/azure-docs-powershell#1755]
1. Is there a sample code for how to use PowerShell Functions concurrent worker process? 

2. When should one use this over PowerShell's built-in parallelization features like [`ForEach-Object -Parallel`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/foreach-object?view=powershell-7.1#example-15--writing-errors-with-parallel-execution), jobs, runspaces etc? 

3. And why is the `-UseNewRunspace` parameter for `ForEach-Object` supported on PowerShell 7.1 on a PC but not on Azure Functions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efae763f-03a9-b3b0-e7ad-52f9b1559438
* Version Independent ID: 2afd9c78-e5b0-5d34-b809-47d9576399d0
* Content: [PowerShell developer reference for Azure Functions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell?tabs=portal#concurrency)
* Content Source: [articles/azure-functions/functions-reference-powershell.md](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/azure-functions/functions-reference-powershell.md)
* Service: **azure-functions**
* GitHub Login: @eamonoreilly
* Microsoft Alias: **glenga**

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by mikefrobbins** [comment]
@Karishma-Tiwari-MSFT Can this issue be moved to the [azure-docs repo](https://github.com/MicrosoftDocs/azure-docs) since that is where the referenced article resides?

The author of that particular article may not respond to the issue in this repo.

@Ayanmullick For future reference, clicking on the "Submit and view feedback for 'This page'" is the best way to make sure your issue is properly triaged. The owner of the article will reach out to the Azure PowerShell team if they need our assistance.
![image](https://user-images.githubusercontent.com/6719572/113717996-d4e3aa80-96b1-11eb-8c03-63499be38647.png)

**Comment by Karishma-Tiwari-MSFT** [comment]
@Ayanmullick It is not supported to move an issue from one repo to another. Please open a new issue on the azure-docs-repo by going to the specific document and clicking on This page under Feedback as shared in the comment above.

We will now close this issue. If there are further questions regarding this matter, please tag me in a comment. I will reopen it and we will gladly continue the discussion.

**Comment by Ayanmullick** [comment]
@Karishma-Tiwari-MSFT, I've been previously asked to contact the PowerShell team directly due to lack of that co-ordination and since that page repo is a generic repo for non-PowerShell docs too.

Please refer: https://github.com/Azure/azure-powershell/issues/10915#issuecomment-574876806

@eamonoreilly, Which repo would you prefer to address this on? @mikefrobbins could you approve reopening issue?

**Comment by mikefrobbins** [comment]
@Ayanmullick As a best practice, file documentation-related issues in the repo where the doc resides. Service teams own the documentation for their particular service and many have their own content developers. The Azure PowerShell team partners with service team content developers when an Azure PowerShell subject matter expert is needed from a documentation standpoint.

The issue where you were directed to the Azure PowerShell team is unrelated and it appears that you were directed to them as part of the triage process for that particular issue.

Since this issue is about running PowerShell commands inside of Azure Functions, an issue should be logged with the service team since they're the subject matter experts for their service. The PowerShell team may have to assist them with the specifics about their language features which are outside of the scope of Azure PowerShell.

**Comment by Ayanmullick** [comment]
@mikefrobbins, ok. Thanks for pointing out. Now there are `PowerShell`-related repositories under the `MicrosoftDocs`, `Azure` and `PowerShell` accounts. A lot more today than the last time I checked. Will resubmit this issue in the `Azure
/azure-functions-powershell-worker` repository.
