### ISSUE TITLE
Mandate Uninstallation of older Azure Powershell from Visual Studio Installer

### ISSUE THREAD

**Issue by arsdragonfly** [MicrosoftDocs/azure-docs-powershell#1855]
Visual Studio might install an older version (2018) of Azure Powershell into the system. This older version needs to be uninstalled via Visual Studio Installer first before installing the latest version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc294cf9-671e-dc74-2f74-90a775cb0187
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install the Azure Az PowerShell module with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-6.3.0)
* Content Source: [docs-conceptual/azps-6.3.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-6.3.0/install-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by kobulloc-MSFT** [comment]
@arsdragonfly Thank you for your feedback!  We are investigating and will get back to you shortly.

**Comment by kobulloc-MSFT** [comment]
@arsdragonfly Windows 10 typically comes with PowerShell 5.0 or 5.1 depending on the version.  It looks like the Azure development workload for Visual Studio 2019 (tested with Pro) includes Azure Powershell (Developer PowerShell for VS 2019).

![image](https://user-images.githubusercontent.com/37556655/128420660-e61cebe5-0cca-4462-b556-ae42f60c1183.png)

After installing Visual Studio 2019 Pro with the Azure workload I'm seeing some odd behavior and will continue to investigate.

**Comment by kobulloc-MSFT** [comment]
@arsdragonfly It looks like Visual Studio 2019 and the Azure development workload with Azure Powershell installs AzureRM and you run into issues with both on the same system:

https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-6.3.0#az-and-azurerm-coexistence

![image](https://user-images.githubusercontent.com/37556655/128434617-5a4f005d-81bd-450a-b893-725577d20080.png)

**Comment by arsdragonfly** [comment]
Correct. Azure PowerShell from Visual Studio is AzureRM, which prevents the
latest version from being installed.

**Comment by kobulloc-MSFT** [comment]
@arsdragonfly I'll update the documentation so that others don't run into this.  Thank you for bringing this to our attention!

My repro:

1. Created a fresh Windows 10 VM with PowerShell 5.1 installed by default
2. Installed Visual Studio 2019 with the Azure development workload which includes Azure PowerShell (and that in turn installs the AzureRM module)
3. Installed PowerShell 7
4. Attempted to run Az PowerShell module commands (example: `Connect-AzAccount`) which failed
5. Uninstalled Microsoft Azure PowerShell via Add/Remove Apps & features
6. Installed the Az PowerShell module on PowerShell 7 using Install-Module (`Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force`)
7. Az PowerShell module commands execute successfully

![image](https://user-images.githubusercontent.com/37556655/128644055-99ad2df7-3a5c-43c1-9dfa-c73ef930b460.png)

![image](https://user-images.githubusercontent.com/37556655/128644071-1072cecf-d088-47ef-9ec5-ae4e6846b6c4.png)

![image](https://user-images.githubusercontent.com/37556655/128644082-599f666a-6e7b-4aa8-b03d-87f744ed70cd.png)
