### ISSUE TITLE
Inconsistent documentation for uninstalling old versions

### ISSUE THREAD

**Issue by jiasli** [MicrosoftDocs/azure-docs-powershell#1911]
This doc https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-6.4.0#update-the-azure-powershell-module says:

> To remove **old versions** of the Az PowerShell module from your system, see [Uninstall the Azure PowerShell module](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-6.4.0). 

But the link https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-6.4.0#feedback only shows how to uninstall **all versions**, instead of **only old versions**.

> Uninstallation can be complicated if you have more than one version of the Az PowerShell module installed. Because of this complexity, we only support uninstalling all versions of the Az PowerShell module that are currently installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7a2bfe1-b332-e523-007b-5216111343ca
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-6.4.0#feedback)
* Content Source: [docs-conceptual/azps-6.4.0/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-6.4.0/uninstall-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by MonikaReddy-MSFT** [comment]
@jiasli - Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can update the document accordingly.

**Comment by mikefrobbins** [comment]
@jiasli The "Update the Azure PowerShell module" section of the installation documentation has been updated to reflect that we only support uninstalling all versions of the Az PowerShell module.

This policy is in place because uninstalling the Az PowerShell module version 6.3.0 would also uninstall the following modules that are required by the Az PowerShell module version 6.4.0.

Az.Advisor version 1.1.1
Az.AnalysisServices version 1.1.4
Az.AppConfiguration version 1.0.0
Az.ApplicationInsights version 1.2.0
Az.Batch version 3.1.0
Az.Billing version 2.0.0
Az.CognitiveServices version 1.9.0
Az.ContainerInstance version 2.1.0
Az.ContainerRegistry version 2.2.3
Az.DataBoxEdge version 1.1.0
Az.Databricks version 1.1.0
Az.DataLakeAnalytics version 1.0.2
Az.DataLakeStore version 1.3.0
Az.DataShare version 1.0.0
Az.DesktopVirtualization version 3.0.0
Az.DeploymentManager version 1.1.0
Az.DevTestLabs version 1.0.2
Az.Dns version 1.1.2
Az.EventGrid version 1.3.0
Az.EventHub version 1.8.0
Az.FrontDoor version 1.8.0
Az.Functions version 3.1.0
Az.HDInsight version 4.3.0
Az.HealthcareApis version 1.3.1
Az.IotHub version 2.7.3
Az.Kusto version 2.0.0
Az.LogicApp version 1.5.0
Az.MachineLearning version 1.1.3
Az.Maintenance version 1.1.1
Az.ManagedServices version 2.0.0
Az.MarketplaceOrdering version 1.0.2
Az.Media version 1.1.1
Az.Monitor version 2.7.0
Az.NotificationHubs version 1.1.1
Az.OperationalInsights version 2.3.0
Az.PolicyInsights version 1.4.1
Az.PowerBIEmbedded version 1.1.2
Az.PrivateDns version 1.0.3
Az.RedisCache version 1.5.0
Az.RedisEnterpriseCache version 1.0.0
Az.Relay version 1.0.3
Az.ResourceMover version 1.0.0
Az.Security version 1.0.0
Az.ServiceBus version 1.5.0
Az.ServiceFabric version 3.0.1
Az.SignalR version 1.3.0
Az.SqlVirtualMachine version 1.1.0
Az.StreamAnalytics version 2.0.0
Az.Support version 1.0.0
Az.TrafficManager version 1.0.4
