### ISSUE TITLE
Cannot find type [Microsoft.Azure.Commands.ActiveDirectory.PSADPasswordCredential]: verify that the assembly containing this type is loaded.

### ISSUE THREAD

**Issue by ToSur** [MicrosoftDocs/azure-docs-powershell#2029]
Hi community,

We are running a script which includes the creation of credentials : 

$credential = New-Object -TypeName Microsoft.Azure.Commands.ActiveDirectory.PSADPasswordCredential -Property @{ StartDate=Get-Date; EndDate=Get-Date -Year 2024; Password="Password"}

=> but it results in the error message _"New-Object : Cannot find type [Microsoft.Azure.Commands.ActiveDirectory.PSADPasswordCredential]: verify that the
assembly containing this type is loaded."_

Getting the latest module is resulting it the same behavior and even in the azure cloud-shell, same error message.

Any idea?

Tom

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for your question. Please provide us with the link to the documentation you are referring to so we can better assist.

**Comment by ToSur** [comment]
The documentation I4m referring to : [https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.commands.activedirectory.psadpasswordcredential?view=az-ps-6](url)

**Comment by mikefrobbins** [comment]
The referenced article is for verion 6.x of the Az PowerShell module. Your code works as designed with that version. Beginning with Az version 7.x, the object type changed due to the migration from the Azure AD API to the Microsoft Graph API.

For more information, see [Azure AD to Microsoft Graph migration changes in Azure PowerShell](https://docs.microsoft.com/powershell/azure/azps-msgraph-migration-changes).

Related issue: Azure/azure-powershell#16671
