### ISSUE TITLE
Update-AzKeyVault documentation is ambiguous about PublicNetworkAccess "Allow" behavior

### ISSUE THREAD

**Issue by chitturs** [MicrosoftDocs/azure-docs-powershell#2883]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/az.keyvault/update-azkeyvault?view=azps-11.2.0&viewFallbackFrom=azps-11.0.0.

### Summary

https://learn.microsoft.com/en-us/powershell/module/az.keyvault/update-azkeyvault?view=azps-11.2.0&viewFallbackFrom=azps-11.0.0 has this blurb for PublicNetworkAccess.

_-PublicNetworkAccess
Specifies whether the vault will accept traffic from public internet. If set to 'disabled' all traffic except private endpoint traffic and that that originates from trusted services will be blocked. This will override the set firewall rules, meaning that even if the firewall rules are present we will not honor the rules._

It is not clear how it interacts with firewall rules if we set this to "Allow". My testing shows that "Allow" **does not** allow public network access if firewall rules are present.

### Suggested Fix

_-PublicNetworkAccess
Specifies whether the vault will accept traffic from public internet. If set to 'disabled' all traffic except private endpoint traffic and that that originates from trusted services will be blocked. This will override the set firewall rules, meaning that even if the firewall rules are present we will not honor the rules._

If set to "Allow", this will still honor any firewall rules and block traffic.

**Comment by AjayBathini-MSFT** [comment]
@chitturs 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by mikefrobbins** [comment]
@chitturs This issue references the autogenerated reference documentation for [Update-AzKeyVault](https://github.com/Azure/azure-powershell/blob/main/src/KeyVault/KeyVault/help/Update-AzKeyVault.md). Please [log an issue in the Azure-Powershell source repo](https://github.com/Azure/azure-powershell/issues/new?template=4-AZ-DOC-BUG.yml&pageUrl=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fpowershell%2Fmodule%2Faz.keyvault%2Fupdate-azkeyvault%3Fview%3Dazps-11.2.0&pageQueryParams=%3Fview%3Dazps-11.2.0&contentSourceUrl=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-powershell%2Fblob%2Fmain%2Fsrc%2FKeyVault%2FKeyVault%2Fhelp%2FUpdate-AzKeyVault.md&documentVersionIndependentId=63b9732d-554f-bb4b-4daf-163a7b25dfbf&feedback=%0A%0A%5BEnter+feedback+here%5D%0A&author=%40mikefrobbins&metadata=*+ID%3A+3efee5dc-aa49-6e16-78ca-23de68dd9692+%0A*+Service%3A+**key-vault**) so our developers can correct the source for the autogeneration process.

Reporting issues via the links at the bottom of each documentation page automatically logs the issue in the appropriate repo:

![image](https://github.com/MicrosoftDocs/azure-docs-powershell/assets/6719572/f189867a-09a5-4bd7-94e2-668e3392d6f0)

We will proceed with closing this issue since the content in this repo is not the source, and changes will be overwritten when future versions are published.
